blank_issues_enabled: true
contact_links:
  - name: Community Discussions
    url: https://github.com/orgs/Project-Aquarius/discussions
    about: Use this for general questions, ideas, and feedback.
